-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Sonder.Object exposing (Game(..), Player(..))


type Game
    = Game


type Player
    = Player
