-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Sonder.ScalarCodecs exposing (Id, JSONString, codecs)

import Json.Decode as Decode exposing (Decoder)
import Sonder.Scalar exposing (defaultCodecs)


type alias Id =
    Sonder.Scalar.Id


type alias JSONString =
    Sonder.Scalar.JSONString


codecs : Sonder.Scalar.Codecs Id JSONString
codecs =
    Sonder.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecJSONString = defaultCodecs.codecJSONString
        }
