# Generated by Django 2.2 on 2019-04-14 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190414_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irwinreport',
            name='owner',
        ),
        migrations.AddField(
            model_name='irwinreportrequiredgame',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irwinreportrequiredgame',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.AnalysisSource'),
        ),
    ]
