# Generated by Django 2.2 on 2019-04-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_gametag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='source_pgn',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
