# Generated by Django 2.2 on 2019-04-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_game_source_pgn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_analyzed',
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
