# Generated by Django 2.2 on 2019-04-15 05:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20190415_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='moves',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='moves_blur',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='moves_emt',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='moves_masterdb_matches',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='source_pgn',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_control',
            field=models.CharField(default='', max_length=8),
        ),
    ]
