# Generated by Django 2.2 on 2019-04-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20190415_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameanalysis',
            name='nodes',
        ),
    ]
