# Generated by Django 2.2.5 on 2019-09-02 14:13

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0008_remove_gameanalysis_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('all_games', 'all_games'), ('custom', 'custom')], max_length=16)),
                ('name', models.CharField(default='', max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('sample_total_cpl', models.PositiveIntegerField(default=0)),
                ('t1_total', models.PositiveIntegerField(default=0)),
                ('t1_count', models.PositiveIntegerField(default=0)),
                ('t2_total', models.PositiveIntegerField(default=0)),
                ('t2_count', models.PositiveIntegerField(default=0)),
                ('t3_total', models.PositiveIntegerField(default=0)),
                ('t3_count', models.PositiveIntegerField(default=0)),
                ('min_rating', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('max_rating', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('game_list', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('cp_loss_count', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('cp_loss_total', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Player')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
