# Generated by Django 2.2.9 on 2019-12-26 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_crreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crreport',
            name='report_type',
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_games', models.PositiveIntegerField()),
                ('tags', models.ManyToManyField(to='analysis.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='crreport',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Criteria'),
        ),
    ]
