# Generated by Django 2.2 on 2019-05-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=models.CharField(max_length=1024),
        ),
        migrations.DeleteModel(
            name='OAuth1Token',
        ),
    ]
