-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Sonder.Object.CRReport exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Sonder.InputObject
import Sonder.Interface
import Sonder.Object
import Sonder.Scalar
import Sonder.ScalarCodecs
import Sonder.Union


{-| -}
player : SelectionSet decodesTo Sonder.Object.Player -> SelectionSet (Maybe decodesTo) Sonder.Object.CRReport
player object_ =
    Object.selectionForCompositeField "player" [] object_ (identity >> Decode.nullable)


{-| -}
completed : SelectionSet Bool Sonder.Object.CRReport
completed =
    Object.selectionForField "Bool" "completed" [] Decode.bool


{-| -}
sampleSize : SelectionSet Int Sonder.Object.CRReport
sampleSize =
    Object.selectionForField "Int" "sampleSize" [] Decode.int


{-| -}
sampleTotalCpl : SelectionSet Int Sonder.Object.CRReport
sampleTotalCpl =
    Object.selectionForField "Int" "sampleTotalCpl" [] Decode.int


{-| -}
t1Total : SelectionSet Int Sonder.Object.CRReport
t1Total =
    Object.selectionForField "Int" "t1Total" [] Decode.int


{-| -}
t1Count : SelectionSet Int Sonder.Object.CRReport
t1Count =
    Object.selectionForField "Int" "t1Count" [] Decode.int


{-| -}
t2Total : SelectionSet Int Sonder.Object.CRReport
t2Total =
    Object.selectionForField "Int" "t2Total" [] Decode.int


{-| -}
t2Count : SelectionSet Int Sonder.Object.CRReport
t2Count =
    Object.selectionForField "Int" "t2Count" [] Decode.int


{-| -}
t3Total : SelectionSet Int Sonder.Object.CRReport
t3Total =
    Object.selectionForField "Int" "t3Total" [] Decode.int


{-| -}
t3Count : SelectionSet Int Sonder.Object.CRReport
t3Count =
    Object.selectionForField "Int" "t3Count" [] Decode.int


{-| -}
minRating : SelectionSet (Maybe Int) Sonder.Object.CRReport
minRating =
    Object.selectionForField "(Maybe Int)" "minRating" [] (Decode.int |> Decode.nullable)


{-| -}
maxRating : SelectionSet (Maybe Int) Sonder.Object.CRReport
maxRating =
    Object.selectionForField "(Maybe Int)" "maxRating" [] (Decode.int |> Decode.nullable)


{-| -}
cpLossTotal : SelectionSet Int Sonder.Object.CRReport
cpLossTotal =
    Object.selectionForField "Int" "cpLossTotal" [] Decode.int


t1Percentage : SelectionSet Float Sonder.Object.CRReport
t1Percentage =
    Object.selectionForField "Float" "t1Percentage" [] Decode.float


t2Percentage : SelectionSet Float Sonder.Object.CRReport
t2Percentage =
    Object.selectionForField "Float" "t2Percentage" [] Decode.float


t3Percentage : SelectionSet Float Sonder.Object.CRReport
t3Percentage =
    Object.selectionForField "Float" "t3Percentage" [] Decode.float


gameList : SelectionSet (List String) Sonder.Object.CRReport
gameList =
    Object.selectionForField "(List String)" "gameList" [] (Decode.string |> Decode.list)


cpLossCount : SelectionSet decodesTo Sonder.Object.CPLoss -> SelectionSet (List decodesTo) Sonder.Object.CRReport
cpLossCount object_ =
    Object.selectionForCompositeField "cpLossCount" [] object_ (identity >> Decode.list)
