-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Sonder.Object.Game exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Sonder.InputObject
import Sonder.Interface
import Sonder.Object
import Sonder.Scalar
import Sonder.ScalarCodecs
import Sonder.Union


{-| -}
id : SelectionSet Sonder.ScalarCodecs.Id Sonder.Object.Game
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Sonder.ScalarCodecs.codecs |> Sonder.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
lichessId : SelectionSet String Sonder.Object.Game
lichessId =
    Object.selectionForField "String" "lichessId" [] Decode.string


{-| -}
whitePlayer : SelectionSet decodesTo Sonder.Object.Player -> SelectionSet decodesTo Sonder.Object.Game
whitePlayer object_ =
    Object.selectionForCompositeField "whitePlayer" [] object_ identity


{-| -}
blackPlayer : SelectionSet decodesTo Sonder.Object.Player -> SelectionSet decodesTo Sonder.Object.Game
blackPlayer object_ =
    Object.selectionForCompositeField "blackPlayer" [] object_ identity


{-| -}
timeControl : SelectionSet String Sonder.Object.Game
timeControl =
    Object.selectionForField "String" "timeControl" [] Decode.string


{-| -}
sourcePgn : SelectionSet String Sonder.Object.Game
sourcePgn =
    Object.selectionForField "String" "sourcePgn" [] Decode.string


{-| -}
moves : SelectionSet (Maybe Sonder.ScalarCodecs.JSONString) Sonder.Object.Game
moves =
    Object.selectionForField "(Maybe ScalarCodecs.JSONString)" "moves" [] (Sonder.ScalarCodecs.codecs |> Sonder.Scalar.unwrapCodecs |> .codecJSONString |> .decoder |> Decode.nullable)


{-| -}
movesEmt : SelectionSet (Maybe Sonder.ScalarCodecs.JSONString) Sonder.Object.Game
movesEmt =
    Object.selectionForField "(Maybe ScalarCodecs.JSONString)" "movesEmt" [] (Sonder.ScalarCodecs.codecs |> Sonder.Scalar.unwrapCodecs |> .codecJSONString |> .decoder |> Decode.nullable)


{-| -}
movesBlur : SelectionSet (Maybe Sonder.ScalarCodecs.JSONString) Sonder.Object.Game
movesBlur =
    Object.selectionForField "(Maybe ScalarCodecs.JSONString)" "movesBlur" [] (Sonder.ScalarCodecs.codecs |> Sonder.Scalar.unwrapCodecs |> .codecJSONString |> .decoder |> Decode.nullable)


{-| -}
movesMasterdbMatches : SelectionSet (Maybe Sonder.ScalarCodecs.JSONString) Sonder.Object.Game
movesMasterdbMatches =
    Object.selectionForField "(Maybe ScalarCodecs.JSONString)" "movesMasterdbMatches" [] (Sonder.ScalarCodecs.codecs |> Sonder.Scalar.unwrapCodecs |> .codecJSONString |> .decoder |> Decode.nullable)
