module Colors exposing (..)

import Element exposing (rgba255)


-- #####  Color Palette by Paletton.com
-- #####  Palette URL: http://paletton.com/#uid=71T0u0kllllaFw0g0qFqFg0w0aF
--
--
-- *** Primary color:
--
-- shade 0 = #AAAA39 = rgb(170,170, 57) = rgba(170,170, 57,1) = rgb0(0.667,0.667,0.224)
-- shade 1 = #FFFFAA = rgb(255,255,170) = rgba(255,255,170,1) = rgb0(1,1,0.667)
-- shade 2 = #D4D46A = rgb(212,212,106) = rgba(212,212,106,1) = rgb0(0.831,0.831,0.416)
-- shade 3 = #808015 = rgb(128,128, 21) = rgba(128,128, 21,1) = rgb0(0.502,0.502,0.082)
-- shade 4 = #555500 = rgb( 85, 85,  0) = rgba( 85, 85,  0,1) = rgb0(0.333,0.333,0)
--
-- *** Secondary color (1):
--
-- shade 0 = #7B9F35 = rgb(123,159, 53) = rgba(123,159, 53,1) = rgb0(0.482,0.624,0.208)
-- shade 1 = #D4EE9F = rgb(212,238,159) = rgba(212,238,159,1) = rgb0(0.831,0.933,0.624)
-- shade 2 = #A5C663 = rgb(165,198, 99) = rgba(165,198, 99,1) = rgb0(0.647,0.776,0.388)
-- shade 3 = #567714 = rgb( 86,119, 20) = rgba( 86,119, 20,1) = rgb0(0.337,0.467,0.078)
-- shade 4 = #354F00 = rgb( 53, 79,  0) = rgba( 53, 79,  0,1) = rgb0(0.208,0.31,0)
--
-- *** Secondary color (2):
--
-- shade 0 = #882D61 = rgb(136, 45, 97) = rgba(136, 45, 97,1) = rgb0(0.533,0.176,0.38)
-- shade 1 = #CD88AF = rgb(205,136,175) = rgba(205,136,175,1) = rgb0(0.804,0.533,0.686)
-- shade 2 = #AA5585 = rgb(170, 85,133) = rgba(170, 85,133,1) = rgb0(0.667,0.333,0.522)
-- shade 3 = #661141 = rgb(102, 17, 65) = rgba(102, 17, 65,1) = rgb0(0.4,0.067,0.255)
-- shade 4 = #440027 = rgb( 68,  0, 39) = rgba( 68,  0, 39,1) = rgb0(0.267,0,0.153)
--
-- *** Complement color:
--
-- shade 0 = #582A72 = rgb( 88, 42,114) = rgba( 88, 42,114,1) = rgb0(0.345,0.165,0.447)
-- shade 1 = #9775AA = rgb(151,117,170) = rgba(151,117,170,1) = rgb0(0.592,0.459,0.667)
-- shade 2 = #764B8E = rgb(118, 75,142) = rgba(118, 75,142,1) = rgb0(0.463,0.294,0.557)
-- shade 3 = #3D1255 = rgb( 61, 18, 85) = rgba( 61, 18, 85,1) = rgb0(0.239,0.071,0.333)
-- shade 4 = #260339 = rgb( 38,  3, 57) = rgba( 38,  3, 57,1) = rgb0(0.149,0.012,0.224)
--
--
-- #####  Generated by Paletton.com (c) 2002-2014


black =
    rgba255 0 0 0 1


grey =
    rgba255 90 90 90 1


lightGrey =
    rgba255 230 230 230 1


primaryShade0 =
    rgba255 170 170 57 1


primaryShade1 =
    rgba255 255 255 170 1


primaryShade2 =
    rgba255 212 212 106 1


primaryShade3 =
    rgba255 128 128 21 1


primaryShade4 =
    rgba255 85 85 0 1


secondaryShade0 =
    rgba255 123 159 53 1


secondaryShade1 =
    rgba255 212 238 159 1


secondaryShade2 =
    rgba255 165 198 99 1


secondaryShade3 =
    rgba255 86 119 20 1


secondaryShade4 =
    rgba255 53 79 0 1


ternaryShade0 =
    rgba255 136 45 97 1


ternaryShade1 =
    rgba255 205 136 175 1


ternaryShade2 =
    rgba255 170 85 133 1


ternaryShade3 =
    rgba255 102 17 65 1


ternaryShade4 =
    rgba255 68 0 39 1


complementShade0 =
    rgba255 88 42 114 1


complementShade1 =
    rgba255 151 117 170 1


complementShade2 =
    rgba255 118 75 142 1


complementShade3 =
    rgba255 61 18 85 1


complementShade4 =
    rgba255 38 3 57 1
